PiPinPP: Pin Class Reference
Pin Class Reference
A class for controlling GPIO pins on Raspberry Pi.
#include <pin.hpp>
Public Member Functions
Pin (int pin, PinDirection direction, const std::string &chipname="gpiochip0")
Construct a new Pin object with direction.
Pin (int pin, PinMode mode, const std::string &chipname="gpiochip0")
Construct a new Pin object with mode (including pull resistors)
~Pin ()
Destroy the Pin object.
bool write (bool value)
Write a value to the pin.
int read ()
Read the current state of the pin.
Detailed Description
A class for controlling GPIO pins on Raspberry Pi.
This class provides a simple interface for controlling GPIO pins, allowing you to set pins high/low and read their current state.
Definition at line 82 of file pin.hpp.
Constructor & Destructor Documentation
Pin() [1/2]
Pin::Pin (int pin, PinDirection direction, const std::string & chipname = "gpiochip0")
Construct a new Pin object with direction.
Parameters
pin The GPIO pin number to control (0-27 for Raspberry Pi)
direction The direction of the pin (INPUT or OUTPUT)
chipname The name of the GPIO chip (default: "gpiochip0")
Exceptions
std::invalid_argument if pin number is invalid (outside 0-27 range)
std::runtime_error if GPIO chip cannot be opened or line cannot be requested
Note
This constructor does not configure pull resistors. Use PinMode constructor for pull resistors.
Warning
Some pins (0,1,14,15) have special functions and may conflict with other uses.
Definition at line 30 of file pin.cpp.
References map(), OUTPUT, and PIPINPP_LOG_INFO.
Pin() [2/2]
Pin::Pin (int pin, PinMode mode, const std::string & chipname = "gpiochip0")
Construct a new Pin object with mode (including pull resistors)
Parameters
pin The GPIO pin number to control (0-27 for Raspberry Pi)
mode The pin mode including pull resistor configuration
chipname The name of the GPIO chip (default: "gpiochip0")
Exceptions
std::invalid_argument if pin number is invalid (outside 0-27 range)
std::runtime_error if GPIO chip cannot be opened or line cannot be requested
Note
Pull resistor support requires libgpiod 1.4+ and compatible hardware
Warning
Some pins (0,1,14,15) have special functions and may conflict with other uses.
Definition at line 116 of file pin.cpp.
References INPUT_PULLDOWN, INPUT_PULLUP, map(), OUTPUT, and PIPINPP_LOG_INFO.
~Pin()
Pin::~Pin ()
Destroy the Pin object.
This destructor releases any resources held by the Pin object. Automatically releases the GPIO line and closes the chip handle. Safe to call multiple times.
Definition at line 214 of file pin.cpp.
References map(), and PIPINPP_LOG_DEBUG.
Member Function Documentation
read()
int Pin::read ()
Read the current state of the pin.
Reads the digital state of a GPIO pin configured as INPUT.
Returns
int Returns 1 if the pin is HIGH (3.3V), 0 if the pin is LOW (0V), -1 on error
Note
Works on pins configured as INPUT, INPUT_PULLUP, or INPUT_PULLDOWN.
For floating inputs without pull resistors, readings may be unstable.
Pin button(18, PinMode::INPUT_PULLUP);
int state = button.read();
if (state == 0) {
    // Button is pressed (connected to GND)
}
Definition at line 243 of file pin.cpp.
References map().
write()
bool Pin::write (bool value)
Write a value to the pin.
Sets the output state of a GPIO pin configured as OUTPUT.
Parameters
value true to set the pin HIGH (3.3V), false to set it LOW (0V)
Returns
bool Returns true on success, false on failure
Note
Only works on pins configured as OUTPUT. Input pins will return false.
Warning
Ensure external circuitry can handle 3.3V logic levels.
Pin led(17, PinDirection::OUTPUT);
led.write(true);  // Turn LED on
led.write(false); // Turn LED off
Definition at line 231 of file pin.cpp.
References map().
The documentation for this class was generated from the following files:
include/pin.hpp
src/pin.cpp