PiPinPP: PWMManager Class Reference
PWMManager Class Reference
Manages software PWM generation on multiple GPIO pins.
#include <pwm.hpp>
Public Member Functions
void startPWM (int pin, int dutyCycle, int frequency=DEFAULT_PWM_FREQUENCY)
Start PWM output on a GPIO pin.
bool setDutyCycle (int pin, int dutyCycle)
Update the duty cycle of an active PWM pin.
bool stopPWM (int pin)
Stop PWM output on a GPIO pin.
bool isActive (int pin) const
Check if PWM is active on a pin.
size_t getActiveCount () const
Get the number of active PWM outputs.
int getDutyCycle (int pin) const
Get the current duty cycle of a PWM pin.
int getFrequency (int pin) const
Get the current frequency of a PWM pin.
PWMManager (const PWMManager &)=delete
PWMManager & operator= (const PWMManager &)=delete
Static Public Member Functions
static PWMManager & getInstance ()
Get the singleton instance.
Detailed Description
Manages software PWM generation on multiple GPIO pins.
This class is thread-safe and handles multiple PWM outputs simultaneously. Each PWM pin has its own dedicated thread for accurate pulse generation.
Note
This is a singleton class - only one instance exists.
Warning
Software PWM has inherent timing jitter and is not suitable for applications requiring precise timing (e.g., servo control). For servos, use hardware PWM instead.
Definition at line 119 of file pwm.hpp.
Constructor & Destructor Documentation
PWMManager()
PWMManager::PWMManager (const PWMManager &) delete
Member Function Documentation
getActiveCount()
size_t PWMManager::getActiveCount () const
Get the number of active PWM outputs.
Returns
Number of pins with active PWM
Definition at line 136 of file pwm.cpp.
References map().
getDutyCycle()
int PWMManager::getDutyCycle (int pin) const
Get the current duty cycle of a PWM pin.
Parameters
pin GPIO pin number
Returns
Duty cycle (0-255), or -1 if PWM not active on this pin
Definition at line 141 of file pwm.cpp.
References map().
getFrequency()
int PWMManager::getFrequency (int pin) const
Get the current frequency of a PWM pin.
Parameters
pin GPIO pin number
Returns
Frequency in Hz, or -1 if PWM not active on this pin
Definition at line 150 of file pwm.cpp.
References map().
getInstance()
PWMManager & PWMManager::getInstance () static
Get the singleton instance.
Returns
Reference to the global PWMManager instance
Definition at line 38 of file pwm.cpp.
References map().
Referenced by analogWrite().
isActive()
bool PWMManager::isActive (int pin) const
Check if PWM is active on a pin.
Parameters
pin GPIO pin number to check
Returns
true if PWM is active, false otherwise
Definition at line 131 of file pwm.cpp.
References map().
operator=()
PWMManager & PWMManager::operator= (const PWMManager &) delete
setDutyCycle()
bool PWMManager::setDutyCycle (int pin, int dutyCycle)
Update the duty cycle of an active PWM pin.
Parameters
pin GPIO pin number
dutyCycle New duty cycle value (0-255)
Returns
true if duty cycle was updated, false if PWM not active on this pin
Note
This is a fast operation that doesn't restart the PWM thread
Changes take effect on the next PWM cycle
Definition at line 102 of file pwm.cpp.
References map(), and PIPINPP_LOG_DEBUG.
startPWM()
void PWMManager::startPWM (int pin, int dutyCycle, int frequency = DEFAULT_PWM_FREQUENCY)
Start PWM output on a GPIO pin.
Parameters
pin GPIO pin number (0-27 for Raspberry Pi)
dutyCycle Duty cycle value (0-255, where 0=always LOW, 255=always HIGH)
frequency PWM frequency in Hz (default 490Hz)
Exceptions
InvalidPinError if pin number is invalid
GpioAccessError if unable to configure pin
Note
If PWM is already active on this pin, duty cycle is updated
Frequency can only be changed by stopping and restarting PWM
Pin is automatically configured as OUTPUT
Definition at line 55 of file pwm.cpp.
References map(), OUTPUT, PIPINPP_LOG_INFO, and PWMChannel::pwmThread.
Referenced by analogWrite().
stopPWM()
bool PWMManager::stopPWM (int pin)
Stop PWM output on a GPIO pin.
Parameters
pin GPIO pin number to stop PWM on
Returns
true if PWM was stopped, false if PWM was not active
Note
Pin is left in OUTPUT mode, set to LOW
Safe to call even if PWM is not active
Definition at line 116 of file pwm.cpp.
References map(), and PIPINPP_LOG_INFO.
The documentation for this class was generated from the following files:
include/pwm.hpp
src/pwm.cpp