PiPinPP: InterruptManager Class Reference
InterruptManager Class Reference
Manages GPIO interrupts with a background monitoring thread.
#include <interrupts.hpp>
Public Member Functions
void attachInterrupt (int pin, InterruptCallback callback, InterruptMode mode, const std::string &chipname="gpiochip0")
Attach an interrupt handler to a GPIO pin.
bool detachInterrupt (int pin)
Detach an interrupt handler from a GPIO pin.
bool isAttached (int pin) const
Check if an interrupt is attached to a pin.
size_t getActiveCount () const
Get the number of active interrupts.
InterruptManager (const InterruptManager &)=delete
InterruptManager & operator= (const InterruptManager &)=delete
Static Public Member Functions
static InterruptManager & getInstance ()
Get the singleton instance.
Detailed Description
Manages GPIO interrupts with a background monitoring thread.
This class is thread-safe and handles multiple interrupt sources. It uses a single background thread to monitor all registered interrupts and dispatches callbacks when edge events occur.
Note
This is a singleton class - only one instance exists.
Definition at line 119 of file interrupts.hpp.
Constructor & Destructor Documentation
InterruptManager()
InterruptManager::InterruptManager (const InterruptManager &) delete
Member Function Documentation
attachInterrupt()
void InterruptManager::attachInterrupt (int pin, InterruptCallback callback, InterruptMode mode, const std::string & chipname = "gpiochip0")
Attach an interrupt handler to a GPIO pin.
Parameters
pin GPIO pin number (0-27 for Raspberry Pi)
callback Function to call when interrupt triggers
mode Edge detection mode (RISING, FALLING, or CHANGE)
chipname GPIO chip name (default: "gpiochip0")
Exceptions
InvalidPinError if pin number is invalid
GpioAccessError if unable to configure interrupt
std::runtime_error if interrupt already attached to this pin
Note
Pin must not already have an interrupt attached
Callback should be fast and non-blocking
Definition at line 81 of file interrupts.cpp.
References map(), and PIPINPP_LOG_INFO.
Referenced by attachInterrupt().
detachInterrupt()
bool InterruptManager::detachInterrupt (int pin)
Detach an interrupt handler from a GPIO pin.
Parameters
pin GPIO pin number to detach interrupt from
Returns
true if interrupt was detached, false if no interrupt was attached
Note
Safe to call even if no interrupt is attached
Definition at line 185 of file interrupts.cpp.
References map(), and PIPINPP_LOG_INFO.
Referenced by detachInterrupt().
getActiveCount()
size_t InterruptManager::getActiveCount () const
Get the number of active interrupts.
Returns
Number of pins with attached interrupt handlers
Definition at line 213 of file interrupts.cpp.
References map().
getInstance()
InterruptManager & InterruptManager::getInstance () static
Get the singleton instance.
Returns
Reference to the global InterruptManager instance
Definition at line 54 of file interrupts.cpp.
References map().
Referenced by attachInterrupt(), and detachInterrupt().
isAttached()
bool InterruptManager::isAttached (int pin) const
Check if an interrupt is attached to a pin.
Parameters
pin GPIO pin number to check
Returns
true if an interrupt handler is attached, false otherwise
Definition at line 208 of file interrupts.cpp.
References map().
operator=()
InterruptManager & InterruptManager::operator= (const InterruptManager &) delete
The documentation for this class was generated from the following files:
include/interrupts.hpp
src/interrupts.cpp