PiPinPP: src/ArduinoCompat.cpp File Reference
ArduinoCompat.cpp File Reference
Implementation of Arduino-compatible API for Raspberry Pi GPIO.
#include "ArduinoCompat.hpp"
#include "exceptions.hpp"
#include "log.hpp"
#include <unordered_map>
#include <memory>
#include <chrono>
#include <thread>
#include <mutex>
#include "interrupts.hpp"
#include "pwm.hpp"
#include <random>
Classes
struct PinInfo
Functions
void pinMode (int pin, int mode)
Set pin mode (Arduino-style function)
void digitalWrite (int pin, bool value)
Write digital value to pin (Arduino-style function)
int digitalRead (int pin)
Read digital value from pin (Arduino-style function)
int constrain (int x, int min, int max)
Constrain a value between minimum and maximum (Arduino-specific function)
long constrain (long x, long min, long max)
Constrain a value between minimum and maximum (Arduino-specific function)
float constrain (float x, float min, float max)
Constrain a value between minimum and maximum (Arduino-specific function)
long map (long x, long in_min, long in_max, long out_min, long out_max)
Map a value from one range to another (Arduino-specific function)
unsigned long millis ()
unsigned long micros ()
void delayMicroseconds (unsigned int us)
void delay (unsigned long ms)
Delay execution for specified milliseconds (Arduino-style function)
void attachInterrupt (int pin, void(*callback)(), int mode)
void detachInterrupt (int pin)
void analogWrite (int pin, int value)
bool isOutput (int pin)
Check if a pin is configured as OUTPUT.
bool isInput (int pin)
Check if a pin is configured as INPUT.
ArduinoPinMode getMode (int pin)
Get the current mode of a pin.
void digitalToggle (int pin)
Toggle the state of an OUTPUT pin (HIGH↔LOW)
void randomSeed (unsigned long seed)
long random (long max)
long random (long min, long max)
unsigned long pulseIn (int pin, bool state, unsigned long timeout)
void shiftOut (int dataPin, int clockPin, int bitOrder, unsigned char value)
unsigned char shiftIn (int dataPin, int clockPin, int bitOrder)
void tone (int pin, unsigned int frequency, unsigned long duration)
void noTone (int pin)
Variables
static std::unordered_map< int, PinInfo > globalPins
static std::mutex globalPinsMutex
static std::mt19937 randomEngine
static std::mutex randomMutex
Detailed Description
Implementation of Arduino-compatible API for Raspberry Pi GPIO.
Author
Barbatos6669
Date
2025
Copyright (c) 2025 HobbyHacker
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file ArduinoCompat.cpp.
Function Documentation
analogWrite()
void analogWrite (int pin, int value)
Definition at line 244 of file ArduinoCompat.cpp.
References PWMManager::getInstance(), PIPINPP_LOG_INFO, and PWMManager::startPWM().
attachInterrupt()
void attachInterrupt (int pin, void(*)() callback, int mode)
Definition at line 199 of file ArduinoCompat.cpp.
References InterruptManager::attachInterrupt(), CHANGE, FALLING, InterruptManager::getInstance(), PIPINPP_LOG_INFO, and RISING.
constrain() [1/3]
float constrain (float x, float min, float max)
Constrain a value between minimum and maximum (Arduino-specific function)
Parameters
x Input value to constrain
min Minimum allowed value
max Maximum allowed value
Returns
float Value constrained between min and max
Definition at line 139 of file ArduinoCompat.cpp.
constrain() [2/3]
int constrain (int x, int min, int max)
Constrain a value between minimum and maximum (Arduino-specific function)
Parameters
x Input value to constrain
min Minimum allowed value
max Maximum allowed value
Returns
int Value constrained between min and max
Definition at line 117 of file ArduinoCompat.cpp.
constrain() [3/3]
long constrain (long x, long min, long max)
Constrain a value between minimum and maximum (Arduino-specific function)
Parameters
x Input value to constrain
min Minimum allowed value
max Maximum allowed value
Returns
long Value constrained between min and max
Definition at line 128 of file ArduinoCompat.cpp.
delay()
void delay (unsigned long ms)
Delay execution for specified milliseconds (Arduino-style function)
Parameters
ms Delay time in milliseconds
Definition at line 188 of file ArduinoCompat.cpp.
Referenced by tone().
delayMicroseconds()
void delayMicroseconds (unsigned int us)
Definition at line 179 of file ArduinoCompat.cpp.
Referenced by shiftIn(), and shiftOut().
detachInterrupt()
void detachInterrupt (int pin)
Definition at line 232 of file ArduinoCompat.cpp.
References InterruptManager::detachInterrupt(), InterruptManager::getInstance(), and PIPINPP_LOG_INFO.
digitalRead()
int digitalRead (int pin)
Read digital value from pin (Arduino-style function)
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
int 1 for HIGH, 0 for LOW, -1 for error
Definition at line 100 of file ArduinoCompat.cpp.
References globalPins, and globalPinsMutex.
Referenced by pulseIn(), and shiftIn().
digitalToggle()
void digitalToggle (int pin)
Toggle the state of an OUTPUT pin (HIGH↔LOW)
Efficiently toggles pin state without reading current value. Much faster than digitalRead() + digitalWrite().
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Exceptions
PinError if pin not initialized or not OUTPUT
Note
Example:
pinMode(17, OUTPUT);
digitalWrite(17, HIGH);
digitalToggle(17);  // Now LOW
digitalToggle(17);  // Now HIGH
Definition at line 293 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, and OUTPUT.
digitalWrite()
void digitalWrite (int pin, bool value)
Write digital value to pin (Arduino-style function)
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
value HIGH (true) or LOW (false)
Definition at line 84 of file ArduinoCompat.cpp.
References globalPins, and globalPinsMutex.
Referenced by shiftIn(), and shiftOut().
getMode()
ArduinoPinMode getMode (int pin)
Get the current mode of a pin.
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
ArduinoPinMode Current mode of the pin (INPUT, OUTPUT, INPUT_PULLUP, INPUT_PULLDOWN)
Exceptions
PinError if pin is not initialized (pinMode not called)
Definition at line 283 of file ArduinoCompat.cpp.
References globalPins, and globalPinsMutex.
isInput()
bool isInput (int pin)
Check if a pin is configured as INPUT.
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
true if pin is INPUT, INPUT_PULLUP, or INPUT_PULLDOWN
false if pin is not INPUT
Exceptions
PinError if pin is not initialized (pinMode not called)
Definition at line 270 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, INPUT, INPUT_PULLDOWN, and INPUT_PULLUP.
isOutput()
bool isOutput (int pin)
Check if a pin is configured as OUTPUT.
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
true if pin is OUTPUT
false if pin is not OUTPUT
Exceptions
PinError if pin is not initialized (pinMode not called)
Definition at line 260 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, and OUTPUT.
map()
long map (long x, long in_min, long in_max, long out_min, long out_max)
Map a value from one range to another (Arduino-specific function)
Parameters
x Input value to map
in_min Minimum of input range
in_max Maximum of input range
out_min Minimum of output range
out_max Maximum of output range
Returns
long Mapped value
Definition at line 150 of file ArduinoCompat.cpp.
micros()
unsigned long micros ()
Definition at line 171 of file ArduinoCompat.cpp.
millis()
unsigned long millis ()
Definition at line 163 of file ArduinoCompat.cpp.
noTone()
void noTone (int pin)
Definition at line 556 of file ArduinoCompat.cpp.
References PWMManager::getInstance(), globalPins, globalPinsMutex, PinInfo::lastValue, PinInfo::mode, OUTPUT, PinInfo::pin, PIPINPP_LOG_INFO, and PWMManager::stopPWM().
Referenced by tone().
pinMode()
void pinMode (int pin, int mode)
Set pin mode (Arduino-style function)
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
mode INPUT (0) or OUTPUT (1)
Definition at line 49 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, INPUT, INPUT_PULLDOWN, INPUT_PULLUP, PinInfo::lastValue, PinInfo::mode, OUTPUT, PinInfo::pin, and PIPINPP_LOG_INFO.
pulseIn()
unsigned long pulseIn (int pin, bool state, unsigned long timeout)
Definition at line 356 of file ArduinoCompat.cpp.
References digitalRead(), globalPins, globalPinsMutex, and OUTPUT.
Referenced by pulseInLong().
random() [1/2]
long random (long max)
Definition at line 332 of file ArduinoCompat.cpp.
References randomEngine, and randomMutex.
random() [2/2]
long random (long min, long max)
Definition at line 342 of file ArduinoCompat.cpp.
References randomEngine, and randomMutex.
randomSeed()
void randomSeed (unsigned long seed)
Definition at line 326 of file ArduinoCompat.cpp.
References randomEngine, and randomMutex.
shiftIn()
unsigned char shiftIn (int dataPin, int clockPin, int bitOrder)
Definition at line 452 of file ArduinoCompat.cpp.
References delayMicroseconds(), digitalRead(), digitalWrite(), globalPins, globalPinsMutex, HIGH, INPUT, INPUT_PULLDOWN, INPUT_PULLUP, LOW, LSBFIRST, and OUTPUT.
shiftOut()
void shiftOut (int dataPin, int clockPin, int bitOrder, unsigned char value)
Definition at line 407 of file ArduinoCompat.cpp.
References delayMicroseconds(), digitalWrite(), globalPins, globalPinsMutex, HIGH, LOW, LSBFIRST, and OUTPUT.
tone()
void tone (int pin, unsigned int frequency, unsigned long duration)
Definition at line 513 of file ArduinoCompat.cpp.
References delay(), PWMManager::getInstance(), globalPins, globalPinsMutex, noTone(), OUTPUT, PIPINPP_LOG_INFO, and PWMManager::startPWM().
Variable Documentation
globalPins
std::unordered_map<int, PinInfo> globalPins static
Definition at line 45 of file ArduinoCompat.cpp.
Referenced by digitalRead(), digitalToggle(), digitalWrite(), getMode(), isInput(), isOutput(), noTone(), pinMode(), pulseIn(), shiftIn(), shiftOut(), and tone().
globalPinsMutex
std::mutex globalPinsMutex static
Definition at line 47 of file ArduinoCompat.cpp.
Referenced by digitalRead(), digitalToggle(), digitalWrite(), getMode(), isInput(), isOutput(), noTone(), pinMode(), pulseIn(), shiftIn(), shiftOut(), and tone().
randomEngine
std::mt19937 randomEngine static
Definition at line 323 of file ArduinoCompat.cpp.
Referenced by random(), and randomSeed().
randomMutex
std::mutex randomMutex static
Definition at line 324 of file ArduinoCompat.cpp.
Referenced by random(), and randomSeed().