PiPinPP: include/ArduinoCompat.hpp File Reference
ArduinoCompat.hpp File Reference
Arduino-compatible API for Raspberry Pi GPIO.
#include "pin.hpp"
#include <cmath>
Enumerations
enum ArduinoPinMode { INPUT = 0 , OUTPUT = 1 , INPUT_PULLUP = 2 , INPUT_PULLDOWN = 3 }
Functions
void pinMode (int pin, int mode)
Set pin mode (Arduino-style function)
void digitalWrite (int pin, bool value)
Write digital value to pin (Arduino-style function)
int digitalRead (int pin)
Read digital value from pin (Arduino-style function)
void delay (unsigned long ms)
Delay execution for specified milliseconds (Arduino-style function)
int constrain (int x, int min, int max)
Constrain a value between minimum and maximum (Arduino-specific function)
long constrain (long x, long min, long max)
Constrain a value between minimum and maximum (Arduino-specific function)
float constrain (float x, float min, float max)
Constrain a value between minimum and maximum (Arduino-specific function)
long map (long x, long in_min, long in_max, long out_min, long out_max)
Map a value from one range to another (Arduino-specific function)
unsigned long millis ()
unsigned long micros ()
void delayMicroseconds (unsigned int us)
void attachInterrupt (int pin, void(*callback)(), int mode)
void detachInterrupt (int pin)
void analogWrite (int pin, int value)
bool isOutput (int pin)
Check if a pin is configured as OUTPUT.
bool isInput (int pin)
Check if a pin is configured as INPUT.
ArduinoPinMode getMode (int pin)
Get the current mode of a pin.
void digitalToggle (int pin)
Toggle the state of an OUTPUT pin (HIGH↔LOW)
template<typename T >
T sq (T x)
void randomSeed (unsigned long seed)
long random (long max)
long random (long min, long max)
unsigned long bit (unsigned int n)
unsigned long bitRead (unsigned long x, unsigned int n)
void bitWrite (unsigned long &x, unsigned int n, unsigned int b)
void bitSet (unsigned long &x, unsigned int n)
void bitClear (unsigned long &x, unsigned int n)
unsigned char highByte (unsigned int x)
unsigned char lowByte (unsigned int x)
unsigned long pulseIn (int pin, bool state, unsigned long timeout=1000000)
unsigned long pulseInLong (int pin, bool state, unsigned long timeout=1000000)
Measure the length of a pulse on a pin with extended range (Arduino-inspired)
void shiftOut (int dataPin, int clockPin, int bitOrder, unsigned char value)
unsigned char shiftIn (int dataPin, int clockPin, int bitOrder)
void tone (int pin, unsigned int frequency, unsigned long duration=0)
void noTone (int pin)
Variables
constexpr bool HIGH = true
constexpr bool LOW = false
constexpr int RISING = 0
Trigger interrupt on rising edge (LOW to HIGH)
constexpr int FALLING = 1
Trigger interrupt on falling edge (HIGH to LOW)
constexpr int CHANGE = 2
Trigger interrupt on any edge (rising or falling)
constexpr double DEG_TO_RAD = 0.017453292519943295769236907684886
constexpr double RAD_TO_DEG = 57.295779513082320876798154814105
constexpr int LSBFIRST = 0
Least Significant Bit First.
constexpr int MSBFIRST = 1
Most Significant Bit First.
Detailed Description
Arduino-compatible API for Raspberry Pi GPIO.
Author
Barbatos6669
Date
2025
Copyright (c) 2025 HobbyHacker
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition in file ArduinoCompat.hpp.
Enumeration Type Documentation
ArduinoPinMode
enum ArduinoPinMode
Enumerator
INPUT
OUTPUT
INPUT_PULLUP
INPUT_PULLDOWN
Definition at line 37 of file ArduinoCompat.hpp.
Function Documentation
analogWrite()
void analogWrite (int pin, int value)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 244 of file ArduinoCompat.cpp.
References PWMManager::getInstance(), PIPINPP_LOG_INFO, and PWMManager::startPWM().
attachInterrupt()
void attachInterrupt (int pin, void(*)() callback, int mode)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 199 of file ArduinoCompat.cpp.
References InterruptManager::attachInterrupt(), CHANGE, FALLING, InterruptManager::getInstance(), PIPINPP_LOG_INFO, and RISING.
bit()
unsigned long bit (unsigned int n) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 507 of file ArduinoCompat.hpp.
bitClear()
void bitClear (unsigned long & x, unsigned int n) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 581 of file ArduinoCompat.hpp.
bitRead()
unsigned long bitRead (unsigned long x, unsigned int n) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 525 of file ArduinoCompat.hpp.
bitSet()
void bitSet (unsigned long & x, unsigned int n) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 564 of file ArduinoCompat.hpp.
bitWrite()
void bitWrite (unsigned long & x, unsigned int n, unsigned int b) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 543 of file ArduinoCompat.hpp.
constrain() [1/3]
float constrain (float x, float min, float max)
Constrain a value between minimum and maximum (Arduino-specific function)
Parameters
x Input value to constrain
min Minimum allowed value
max Maximum allowed value
Returns
float Value constrained between min and max
Definition at line 139 of file ArduinoCompat.cpp.
constrain() [2/3]
int constrain (int x, int min, int max)
Constrain a value between minimum and maximum (Arduino-specific function)
Parameters
x Input value to constrain
min Minimum allowed value
max Maximum allowed value
Returns
int Value constrained between min and max
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 117 of file ArduinoCompat.cpp.
constrain() [3/3]
long constrain (long x, long min, long max)
Constrain a value between minimum and maximum (Arduino-specific function)
Parameters
x Input value to constrain
min Minimum allowed value
max Maximum allowed value
Returns
long Value constrained between min and max
Definition at line 128 of file ArduinoCompat.cpp.
delay()
void delay (unsigned long ms)
Delay execution for specified milliseconds (Arduino-style function)
Parameters
ms Delay time in milliseconds
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 188 of file ArduinoCompat.cpp.
Referenced by tone().
delayMicroseconds()
void delayMicroseconds (unsigned int us)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 179 of file ArduinoCompat.cpp.
Referenced by shiftIn(), and shiftOut().
detachInterrupt()
void detachInterrupt (int pin)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 232 of file ArduinoCompat.cpp.
References InterruptManager::detachInterrupt(), InterruptManager::getInstance(), and PIPINPP_LOG_INFO.
digitalRead()
int digitalRead (int pin)
Read digital value from pin (Arduino-style function)
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
int 1 for HIGH, 0 for LOW, -1 for error
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 100 of file ArduinoCompat.cpp.
References globalPins, and globalPinsMutex.
Referenced by pulseIn(), and shiftIn().
digitalToggle()
void digitalToggle (int pin)
Toggle the state of an OUTPUT pin (HIGH↔LOW)
Efficiently toggles pin state without reading current value. Much faster than digitalRead() + digitalWrite().
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Exceptions
PinError if pin not initialized or not OUTPUT
Note
Example:
pinMode(17, OUTPUT);
digitalWrite(17, HIGH);
digitalToggle(17);  // Now LOW
digitalToggle(17);  // Now HIGH
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 293 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, and OUTPUT.
digitalWrite()
void digitalWrite (int pin, bool value)
Write digital value to pin (Arduino-style function)
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
value HIGH (true) or LOW (false)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 84 of file ArduinoCompat.cpp.
References globalPins, and globalPinsMutex.
Referenced by shiftIn(), and shiftOut().
getMode()
ArduinoPinMode getMode (int pin)
Get the current mode of a pin.
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
ArduinoPinMode Current mode of the pin (INPUT, OUTPUT, INPUT_PULLUP, INPUT_PULLDOWN)
Exceptions
PinError if pin is not initialized (pinMode not called)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 283 of file ArduinoCompat.cpp.
References globalPins, and globalPinsMutex.
highByte()
unsigned char highByte (unsigned int x) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 598 of file ArduinoCompat.hpp.
isInput()
bool isInput (int pin)
Check if a pin is configured as INPUT.
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
true if pin is INPUT, INPUT_PULLUP, or INPUT_PULLDOWN
false if pin is not INPUT
Exceptions
PinError if pin is not initialized (pinMode not called)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 270 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, INPUT, INPUT_PULLDOWN, and INPUT_PULLUP.
isOutput()
bool isOutput (int pin)
Check if a pin is configured as OUTPUT.
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
Returns
true if pin is OUTPUT
false if pin is not OUTPUT
Exceptions
PinError if pin is not initialized (pinMode not called)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 260 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, and OUTPUT.
lowByte()
unsigned char lowByte (unsigned int x) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 615 of file ArduinoCompat.hpp.
map()
long map (long x, long in_min, long in_max, long out_min, long out_max)
Map a value from one range to another (Arduino-specific function)
Parameters
x Input value to map
in_min Minimum of input range
in_max Maximum of input range
out_min Minimum of output range
out_max Maximum of output range
Returns
long Mapped value
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 150 of file ArduinoCompat.cpp.
micros()
unsigned long micros ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 171 of file ArduinoCompat.cpp.
millis()
unsigned long millis ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 163 of file ArduinoCompat.cpp.
noTone()
void noTone (int pin)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 556 of file ArduinoCompat.cpp.
References PWMManager::getInstance(), globalPins, globalPinsMutex, PinInfo::lastValue, PinInfo::mode, OUTPUT, PinInfo::pin, PIPINPP_LOG_INFO, and PWMManager::stopPWM().
Referenced by tone().
pinMode()
void pinMode (int pin, int mode)
Set pin mode (Arduino-style function)
Thread-safe: Multiple threads can call this function concurrently.
Parameters
pin GPIO pin number
mode INPUT (0) or OUTPUT (1)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 49 of file ArduinoCompat.cpp.
References globalPins, globalPinsMutex, INPUT, INPUT_PULLDOWN, INPUT_PULLUP, PinInfo::lastValue, PinInfo::mode, OUTPUT, PinInfo::pin, and PIPINPP_LOG_INFO.
pulseIn()
unsigned long pulseIn (int pin, bool state, unsigned long timeout = 1000000)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 356 of file ArduinoCompat.cpp.
References digitalRead(), globalPins, globalPinsMutex, and OUTPUT.
Referenced by pulseInLong().
pulseInLong()
unsigned long pulseInLong (int pin, bool state, unsigned long timeout = 1000000) inline
Measure the length of a pulse on a pin with extended range (Arduino-inspired)
Similar to pulseIn() but returns unsigned long for measuring longer pulses. Use this for pulses longer than ~71 minutes.
Parameters
pin GPIO pin number to read
state Pulse state to measure (HIGH or LOW)
timeout Maximum time to wait in microseconds (default: 1000000 = 1 second)
Returns
unsigned long Pulse length in microseconds, or 0 if timeout
Note
Identical to pulseIn() on Raspberry Pi (both return unsigned long)
Provided for Arduino code compatibility
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 702 of file ArduinoCompat.hpp.
References pulseIn().
random() [1/2]
long random (long max)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 332 of file ArduinoCompat.cpp.
References randomEngine, and randomMutex.
random() [2/2]
long random (long min, long max)
Definition at line 342 of file ArduinoCompat.cpp.
References randomEngine, and randomMutex.
randomSeed()
void randomSeed (unsigned long seed)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 326 of file ArduinoCompat.cpp.
References randomEngine, and randomMutex.
shiftIn()
unsigned char shiftIn (int dataPin, int clockPin, int bitOrder)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 452 of file ArduinoCompat.cpp.
References delayMicroseconds(), digitalRead(), digitalWrite(), globalPins, globalPinsMutex, HIGH, INPUT, INPUT_PULLDOWN, INPUT_PULLUP, LOW, LSBFIRST, and OUTPUT.
shiftOut()
void shiftOut (int dataPin, int clockPin, int bitOrder, unsigned char value)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 407 of file ArduinoCompat.cpp.
References delayMicroseconds(), digitalWrite(), globalPins, globalPinsMutex, HIGH, LOW, LSBFIRST, and OUTPUT.
sq()
template<typename T > T sq (T x) inline
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 399 of file ArduinoCompat.hpp.
tone()
void tone (int pin, unsigned int frequency, unsigned long duration = 0)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 513 of file ArduinoCompat.cpp.
References delay(), PWMManager::getInstance(), globalPins, globalPinsMutex, noTone(), OUTPUT, PIPINPP_LOG_INFO, and PWMManager::startPWM().
Variable Documentation
CHANGE
constexpr int CHANGE = 2 constexpr
Trigger interrupt on any edge (rising or falling)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 189 of file ArduinoCompat.hpp.
Referenced by attachInterrupt().
DEG_TO_RAD
constexpr double DEG_TO_RAD = 0.017453292519943295769236907684886 constexpr
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 424 of file ArduinoCompat.hpp.
FALLING
constexpr int FALLING = 1 constexpr
Trigger interrupt on falling edge (HIGH to LOW)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 188 of file ArduinoCompat.hpp.
Referenced by attachInterrupt().
HIGH
constexpr bool HIGH = true constexpr
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 33 of file ArduinoCompat.hpp.
Referenced by shiftIn(), and shiftOut().
LOW
constexpr bool LOW = false constexpr
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 34 of file ArduinoCompat.hpp.
Referenced by shiftIn(), and shiftOut().
LSBFIRST
constexpr int LSBFIRST = 0 constexpr
Least Significant Bit First.
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 773 of file ArduinoCompat.hpp.
Referenced by shiftIn(), and shiftOut().
MSBFIRST
constexpr int MSBFIRST = 1 constexpr
Most Significant Bit First.
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 774 of file ArduinoCompat.hpp.
Referenced by pipinpp::SPIClass::begin().
RAD_TO_DEG
constexpr double RAD_TO_DEG = 57.295779513082320876798154814105 constexpr
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 435 of file ArduinoCompat.hpp.
RISING
constexpr int RISING = 0 constexpr
Trigger interrupt on rising edge (LOW to HIGH)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/ArduinoCompat.hpp.
Definition at line 187 of file ArduinoCompat.hpp.
Referenced by attachInterrupt().