PiPinPP: pipinpp::HardwarePWM Class Reference
pipinpp::HardwarePWM Class Reference
Hardware PWM control via Linux sysfs interface.
#include <HardwarePWM.hpp>
Public Member Functions
HardwarePWM (int chip=0, int channel=0)
Constructor.
~HardwarePWM ()
Destructor - automatically disables and unexports PWM.
bool begin (uint32_t frequencyHz, double initialDutyCycle=0.0)
Initialize hardware PWM with frequency.
void end ()
Disable and unexport PWM channel.
bool isEnabled () const
Check if PWM is currently enabled.
bool setFrequency (uint32_t frequencyHz)
Set PWM frequency in Hz.
bool setDutyCycle (double percent)
Set duty cycle as percentage (0.0-100.0)
bool setDutyCycle8Bit (uint8_t value)
Set duty cycle as 8-bit value (Arduino-compatible)
bool setPeriodNs (uint64_t nanoseconds)
Set PWM period in nanoseconds (direct control)
bool setDutyCycleNs (uint64_t nanoseconds)
Set duty cycle in nanoseconds (direct control)
bool setPolarity (PWMPolarity polarity)
Set PWM polarity.
bool enable ()
Enable PWM output.
bool disable ()
Disable PWM output.
uint32_t getFrequency () const
Get current frequency in Hz.
double getDutyCycle () const
Get current duty cycle percentage.
uint64_t getPeriodNs () const
Get current period in nanoseconds.
uint64_t getDutyCycleNs () const
Get current duty cycle in nanoseconds.
Static Public Member Functions
static bool gpioToPWM (int gpioPin, int &chip, int &channel)
Helper: Convert GPIO pin number to PWM chip/channel.
Detailed Description
Hardware PWM control via Linux sysfs interface.
This class provides jitter-free hardware PWM using the Linux kernel's /sys/class/pwm interface. Ideal for servo control, motor speed control, and applications requiring precise timing.
Note
Thread-safe: All operations are protected by internal mutex
Auto-export: PWM channel is automatically exported/unexported
Pin conflicts: Using hardware PWM on a pin disables other functions
Pin Mapping (Raspberry Pi):
GPIO12 → PWM0 (chip=0, channel=0)
GPIO13 → PWM1 (chip=0, channel=1)
GPIO18 → PWM0 (chip=0, channel=0) - same as GPIO12
GPIO19 → PWM1 (chip=0, channel=1) - same as GPIO13
Definition at line 109 of file HardwarePWM.hpp.
Constructor & Destructor Documentation
HardwarePWM()
pipinpp::HardwarePWM::HardwarePWM (int chip = 0, int channel = 0)
Constructor.
Parameters
chip PWM chip number (usually 0 for Raspberry Pi)
channel PWM channel number (0 or 1)
Definition at line 42 of file HardwarePWM.cpp.
References PIPINPP_LOG_DEBUG.
~HardwarePWM()
pipinpp::HardwarePWM::~HardwarePWM ()
Destructor - automatically disables and unexports PWM.
Definition at line 56 of file HardwarePWM.cpp.
References end().
Member Function Documentation
begin()
bool pipinpp::HardwarePWM::begin (uint32_t frequencyHz, double initialDutyCycle = 0.0)
Initialize hardware PWM with frequency.
Parameters
frequencyHz PWM frequency in Hz (1-25000000)
initialDutyCycle Initial duty cycle percentage (0.0-100.0)
Returns
true on success, false on error
Note
Exports the PWM channel if not already exported
Enables the PWM output
Example:
HardwarePWM servo(0, 0);
servo.begin(50);  // 50Hz for servo control
Definition at line 61 of file HardwarePWM.cpp.
References PIPINPP_LOG_ERROR, and PIPINPP_LOG_INFO.
disable()
bool pipinpp::HardwarePWM::disable ()
Disable PWM output.
Returns
true on success, false on error
Note
Pin goes to LOW (or HIGH if inverted polarity)
Definition at line 320 of file HardwarePWM.cpp.
References PIPINPP_LOG_ERROR.
enable()
bool pipinpp::HardwarePWM::enable ()
Enable PWM output.
Returns
true on success, false on error
Note
Must call begin() first
Definition at line 302 of file HardwarePWM.cpp.
References PIPINPP_LOG_ERROR.
end()
void pipinpp::HardwarePWM::end ()
Disable and unexport PWM channel.
Note
Safe to call multiple times
Definition at line 104 of file HardwarePWM.cpp.
References PIPINPP_LOG_DEBUG.
Referenced by ~HardwarePWM().
getDutyCycle()
double pipinpp::HardwarePWM::getDutyCycle () const
Get current duty cycle percentage.
Returns
Duty cycle percentage (0.0-100.0), or -1.0 on error
Definition at line 348 of file HardwarePWM.cpp.
getDutyCycleNs()
uint64_t pipinpp::HardwarePWM::getDutyCycleNs () const
Get current duty cycle in nanoseconds.
Returns
Duty cycle in nanoseconds, or 0 on error
Definition at line 365 of file HardwarePWM.cpp.
getFrequency()
uint32_t pipinpp::HardwarePWM::getFrequency () const
Get current frequency in Hz.
Returns
Frequency in Hz, or 0 if not initialized
Definition at line 337 of file HardwarePWM.cpp.
getPeriodNs()
uint64_t pipinpp::HardwarePWM::getPeriodNs () const
Get current period in nanoseconds.
Returns
Period in nanoseconds, or 0 on error
Definition at line 359 of file HardwarePWM.cpp.
gpioToPWM()
bool pipinpp::HardwarePWM::gpioToPWM (int gpioPin, int & chip, int & channel) static
Helper: Convert GPIO pin number to PWM chip/channel.
Parameters
gpioPin GPIO pin number (12, 13, 18, or 19)
[out] chip PWM chip number
[out] channel PWM channel number
Returns
true if pin supports hardware PWM, false otherwise
Example:
int chip, channel;
if (HardwarePWM::gpioToPWM(18, chip, channel)) {
    HardwarePWM pwm(chip, channel);
    pwm.begin(1000);
}
Definition at line 371 of file HardwarePWM.cpp.
isEnabled()
bool pipinpp::HardwarePWM::isEnabled () const
Check if PWM is currently enabled.
Returns
true if PWM is enabled, false otherwise
Definition at line 120 of file HardwarePWM.cpp.
setDutyCycle()
bool pipinpp::HardwarePWM::setDutyCycle (double percent)
Set duty cycle as percentage (0.0-100.0)
Parameters
percent Duty cycle percentage (0.0 = always LOW, 100.0 = always HIGH)
Returns
true on success, false on error
Example:
pwm.setDutyCycle(50.0);  // 50% duty cycle
pwm.setDutyCycle(7.5);   // 7.5% for servo center position
Definition at line 182 of file HardwarePWM.cpp.
References PIPINPP_LOG_DEBUG, and PIPINPP_LOG_ERROR.
Referenced by setDutyCycle8Bit().
setDutyCycle8Bit()
bool pipinpp::HardwarePWM::setDutyCycle8Bit (uint8_t value)
Set duty cycle as 8-bit value (Arduino-compatible)
Parameters
value Duty cycle value (0-255)
Returns
true on success, false on error
Note
Converts to percentage: 0 → 0%, 255 → 100%
Example:
pwm.setDutyCycle8Bit(128);  // 50% duty cycle
pwm.setDutyCycle8Bit(255);  // 100% duty cycle
Definition at line 207 of file HardwarePWM.cpp.
References setDutyCycle().
setDutyCycleNs()
bool pipinpp::HardwarePWM::setDutyCycleNs (uint64_t nanoseconds)
Set duty cycle in nanoseconds (direct control)
Parameters
nanoseconds Duty cycle in nanoseconds
Returns
true on success, false on error
Note
Must be less than or equal to period
For advanced users requiring precise pulse width control
Definition at line 250 of file HardwarePWM.cpp.
References PIPINPP_LOG_ERROR, and PIPINPP_LOG_WARNING.
setFrequency()
bool pipinpp::HardwarePWM::setFrequency (uint32_t frequencyHz)
Set PWM frequency in Hz.
Parameters
frequencyHz Frequency in Hz (1-25000000)
Returns
true on success, false on error
Note
Changes take effect immediately
Duty cycle percentage is preserved
Example:
pwm.setFrequency(1000);  // 1kHz PWM
Definition at line 126 of file HardwarePWM.cpp.
References PIPINPP_LOG_DEBUG, and PIPINPP_LOG_ERROR.
setPeriodNs()
bool pipinpp::HardwarePWM::setPeriodNs (uint64_t nanoseconds)
Set PWM period in nanoseconds (direct control)
Parameters
nanoseconds Period in nanoseconds
Returns
true on success, false on error
Note
For advanced users requiring precise period control
Frequency = 1,000,000,000 / period_ns
Definition at line 213 of file HardwarePWM.cpp.
References PIPINPP_LOG_ERROR.
setPolarity()
bool pipinpp::HardwarePWM::setPolarity (PWMPolarity polarity)
Set PWM polarity.
Parameters
polarity Normal or Inversed
Returns
true on success, false on error
Note
Normal = active-high, Inversed = active-low
Definition at line 273 of file HardwarePWM.cpp.
References pipinpp::NORMAL, PIPINPP_LOG_DEBUG, and PIPINPP_LOG_ERROR.
The documentation for this class was generated from the following files:
include/HardwarePWM.hpp
src/HardwarePWM.cpp