PiPinPP: pipinpp::EventPWM Class Reference
pipinpp::EventPWM Class Reference
Event-driven PWM channel with reduced CPU usage.
#include <event_pwm.hpp>
Public Member Functions
EventPWM (int pin)
Constructor.
~EventPWM ()
Destructor - stops PWM and cleans up.
EventPWM (const EventPWM &)=delete
EventPWM & operator= (const EventPWM &)=delete
bool begin (double frequencyHz, double dutyCycle=0.0)
Start PWM with specified frequency.
void end ()
Stop PWM and release resources.
bool setDutyCycle (double dutyCycle)
Set duty cycle as percentage.
bool setDutyCycle8Bit (uint8_t value)
Set duty cycle using 8-bit value (Arduino-style)
bool setFrequency (double frequencyHz)
Change PWM frequency.
double getDutyCycle () const
Get current duty cycle.
double getFrequency () const
Get current frequency.
bool isActive () const
Check if PWM is running.
int getPin () const
Get GPIO pin number.
Detailed Description
Event-driven PWM channel with reduced CPU usage.
Uses hybrid timing: clock_nanosleep() for coarse delays, busy-wait for final precision microseconds.
Definition at line 77 of file event_pwm.hpp.
Constructor & Destructor Documentation
EventPWM() [1/2]
pipinpp::EventPWM::EventPWM (int pin) explicit
Constructor.
Parameters
pin GPIO pin number (0-27)
Exceptions
InvalidPinError if pin number invalid
Definition at line 39 of file event_pwm.cpp.
References PIPINPP_LOG_DEBUG.
~EventPWM()
pipinpp::EventPWM::~EventPWM ()
Destructor - stops PWM and cleans up.
Definition at line 51 of file event_pwm.cpp.
References end().
EventPWM() [2/2]
pipinpp::EventPWM::EventPWM (const EventPWM &) delete
Member Function Documentation
begin()
bool pipinpp::EventPWM::begin (double frequencyHz, double dutyCycle = 0.0)
Start PWM with specified frequency.
Parameters
frequencyHz Frequency in Hz (50-10000)
dutyCycle Initial duty cycle percentage (0.0-100.0)
Returns
true on success
Note
Pin is automatically configured as OUTPUT
Definition at line 55 of file event_pwm.cpp.
References OUTPUT, PIPINPP_LOG_ERROR, and PIPINPP_LOG_INFO.
end()
void pipinpp::EventPWM::end ()
Stop PWM and release resources.
Definition at line 97 of file event_pwm.cpp.
References PIPINPP_LOG_INFO.
Referenced by ~EventPWM().
getDutyCycle()
double pipinpp::EventPWM::getDutyCycle () const
Get current duty cycle.
Returns
Duty cycle percentage (0.0-100.0)
Definition at line 147 of file event_pwm.cpp.
getFrequency()
double pipinpp::EventPWM::getFrequency () const
Get current frequency.
Returns
Frequency in Hz
Definition at line 151 of file event_pwm.cpp.
getPin()
int pipinpp::EventPWM::getPin () const inline
Get GPIO pin number.
Returns
Pin number
Definition at line 155 of file event_pwm.hpp.
isActive()
bool pipinpp::EventPWM::isActive () const
Check if PWM is running.
Returns
true if active
Definition at line 155 of file event_pwm.cpp.
operator=()
EventPWM& pipinpp::EventPWM::operator= (const EventPWM &) delete
setDutyCycle()
bool pipinpp::EventPWM::setDutyCycle (double dutyCycle)
Set duty cycle as percentage.
Parameters
dutyCycle Percentage (0.0 = always LOW, 100.0 = always HIGH)
Returns
true on success
Definition at line 120 of file event_pwm.cpp.
References PIPINPP_LOG_DEBUG, and PIPINPP_LOG_ERROR.
Referenced by setDutyCycle8Bit().
setDutyCycle8Bit()
bool pipinpp::EventPWM::setDutyCycle8Bit (uint8_t value)
Set duty cycle using 8-bit value (Arduino-style)
Parameters
value 0-255 (0 = 0%, 255 = 100%)
Returns
true on success
Note
Compatible with analogWrite() API
Definition at line 131 of file event_pwm.cpp.
References setDutyCycle().
setFrequency()
bool pipinpp::EventPWM::setFrequency (double frequencyHz)
Change PWM frequency.
Parameters
frequencyHz New frequency in Hz (50-10000)
Returns
true on success
Definition at line 136 of file event_pwm.cpp.
References PIPINPP_LOG_DEBUG, and PIPINPP_LOG_ERROR.
The documentation for this class was generated from the following files:
include/event_pwm.hpp
src/event_pwm.cpp