PiPinPP: pipinpp::WireClass Class Reference
pipinpp::WireClass Class Reference
Arduino-compatible I2C master communication class.
#include <Wire.hpp>
Public Member Functions
WireClass ()
Construct Wire object.
~WireClass ()
Destroy Wire object.
WireClass (const WireClass &)=delete
WireClass & operator= (const WireClass &)=delete
bool begin ()
bool begin (int busNumber)
void end ()
Close I2C interface.
void beginTransmission (uint8_t address)
uint8_t endTransmission (bool sendStop=true)
uint8_t endTransmission ()
End transmission (simplified)
size_t write (uint8_t data)
size_t write (const uint8_t *data, size_t length)
size_t requestFrom (uint8_t address, size_t quantity, bool sendStop=true)
size_t requestFrom (uint8_t address, size_t quantity)
Request bytes from I2C device (simplified)
size_t available ()
int read ()
int peek ()
bool setClock (uint32_t frequency)
uint32_t getClock () const
Get current I2C clock speed.
int readRegister (uint8_t address, uint8_t reg)
bool writeRegister (uint8_t address, uint8_t reg, uint8_t value)
int readRegisters (uint8_t address, uint8_t reg, uint8_t *buffer, size_t length)
std::vector< uint8_t > scan ()
bool exists (uint8_t address)
Detailed Description
Arduino-compatible I2C master communication class.
Implements the Arduino Wire library API for I2C communication on Raspberry Pi. Uses Linux i2c-dev driver for hardware I2C access.
Standard usage pattern:
Wire.begin();                          // Initialize as master
Wire.beginTransmission(0x68);          // Start transmission to device
Wire.write(0x00);                      // Write register address
Wire.write(0x42);                      // Write data
Wire.endTransmission();                // End transmission
Wire.requestFrom(0x68, 2);             // Request 2 bytes
if (Wire.available()) {
    uint8_t data = Wire.read();        // Read received data
}
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 77 of file Wire.hpp.
Constructor & Destructor Documentation
WireClass() [1/2]
pipinpp::WireClass::WireClass ()
Construct Wire object.
Creates an I2C interface object. Call begin() to initialize.
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 44 of file Wire.cpp.
~WireClass()
pipinpp::WireClass::~WireClass ()
Destroy Wire object.
Closes I2C device if open.
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 55 of file Wire.cpp.
References end().
WireClass() [2/2]
pipinpp::WireClass::WireClass (const WireClass &) delete
Member Function Documentation
available()
size_t pipinpp::WireClass::available ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 243 of file Wire.cpp.
Referenced by write().
begin() [1/2]
bool pipinpp::WireClass::begin ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 63 of file Wire.cpp.
begin() [2/2]
bool pipinpp::WireClass::begin (int busNumber)
Definition at line 92 of file Wire.cpp.
beginTransmission()
void pipinpp::WireClass::beginTransmission (uint8_t address)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 132 of file Wire.cpp.
Referenced by exists(), readRegister(), readRegisters(), and writeRegister().
end()
void pipinpp::WireClass::end ()
Close I2C interface.
Closes the I2C device file descriptor.
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 114 of file Wire.cpp.
Referenced by ~WireClass().
endTransmission() [1/2]
uint8_t pipinpp::WireClass::endTransmission ()
End transmission (simplified)
Always sends STOP condition.
Returns
Error code (same as endTransmission(true))
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 170 of file Wire.cpp.
Referenced by exists(), readRegister(), readRegisters(), and writeRegister().
endTransmission() [2/2]
uint8_t pipinpp::WireClass::endTransmission (bool sendStop = true)
Definition at line 139 of file Wire.cpp.
References write().
exists()
bool pipinpp::WireClass::exists (uint8_t address)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 361 of file Wire.cpp.
References beginTransmission(), and endTransmission().
Referenced by scan().
getClock()
uint32_t pipinpp::WireClass::getClock () const
Get current I2C clock speed.
Returns
Current clock frequency in Hz
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 291 of file Wire.cpp.
operator=()
WireClass& pipinpp::WireClass::operator= (const WireClass &) delete
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
peek()
int pipinpp::WireClass::peek ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 263 of file Wire.cpp.
read()
int pipinpp::WireClass::read ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 253 of file Wire.cpp.
Referenced by readRegister(), readRegisters(), and requestFrom().
readRegister()
int pipinpp::WireClass::readRegister (uint8_t address, uint8_t reg)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 299 of file Wire.cpp.
References beginTransmission(), endTransmission(), read(), requestFrom(), and write().
readRegisters()
int pipinpp::WireClass::readRegisters (uint8_t address, uint8_t reg, uint8_t * buffer, size_t length)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 322 of file Wire.cpp.
References beginTransmission(), endTransmission(), read(), requestFrom(), and write().
requestFrom() [1/2]
size_t pipinpp::WireClass::requestFrom (uint8_t address, size_t quantity)
Request bytes from I2C device (simplified)
Always sends STOP after read.
Parameters
address 7-bit I2C slave address
quantity Number of bytes to request
Returns
Number of bytes received
Definition at line 239 of file Wire.cpp.
References requestFrom().
requestFrom() [2/2]
size_t pipinpp::WireClass::requestFrom (uint8_t address, size_t quantity, bool sendStop = true)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 207 of file Wire.cpp.
References read().
Referenced by readRegister(), readRegisters(), and requestFrom().
scan()
std::vector< uint8_t > pipinpp::WireClass::scan ()
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 347 of file Wire.cpp.
References exists().
setClock()
bool pipinpp::WireClass::setClock (uint32_t frequency)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 277 of file Wire.cpp.
write() [1/2]
size_t pipinpp::WireClass::write (const uint8_t * data, size_t length)
Definition at line 189 of file Wire.cpp.
References available().
write() [2/2]
size_t pipinpp::WireClass::write (uint8_t data)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 178 of file Wire.cpp.
Referenced by endTransmission(), readRegister(), readRegisters(), and writeRegister().
writeRegister()
bool pipinpp::WireClass::writeRegister (uint8_t address, uint8_t reg, uint8_t value)
Examples
/home/runner/work/PiPinPP/PiPinPP/include/Wire.hpp.
Definition at line 314 of file Wire.cpp.
References beginTransmission(), endTransmission(), and write().
The documentation for this class was generated from the following files:
include/Wire.hpp
src/Wire.cpp