PiPinPP: pipinpp::SerialPort Class Reference
pipinpp::SerialPort Class Reference
Arduino-compatible Serial communication class for Raspberry Pi.
#include <Serial.hpp>
Public Member Functions
SerialPort ()
Constructor.
~SerialPort ()
Destructor - automatically closes port if open.
bool begin (unsigned long baudRate, const std::string &device="/dev/ttyUSB0")
Open serial port with specified baud rate.
void end ()
Close serial port.
bool isOpen () const
Check if serial port is open and ready.
int available ()
Get number of bytes available for reading.
int read ()
Read single byte from serial port (blocking)
int peek ()
Peek at next byte without removing from buffer.
size_t write (uint8_t byte)
Write single byte to serial port.
size_t write (const uint8_t *buffer, size_t size)
Write buffer of bytes to serial port.
size_t write (const std::string &str)
Write string to serial port.
size_t print (const std::string &data)
Print data to serial port (no newline)
size_t print (int num)
Print integer to serial port (no newline)
size_t print (int num, PrintFormat format)
Print integer to serial port with format (no newline)
size_t print (long num)
Print long integer to serial port (no newline)
size_t print (long num, PrintFormat format)
Print long integer to serial port with format (no newline)
size_t print (unsigned int num)
Print unsigned integer to serial port (no newline)
size_t print (unsigned int num, PrintFormat format)
Print unsigned integer to serial port with format (no newline)
size_t print (double num, int decimals=2)
Print floating-point number to serial port (no newline)
size_t println (const std::string &data)
Print data to serial port with newline.
size_t println (int num)
Print integer to serial port with newline.
size_t println (int num, PrintFormat format)
Print integer to serial port with format and newline.
size_t println (long num)
Print long integer to serial port with newline.
size_t println (long num, PrintFormat format)
Print long integer to serial port with format and newline.
size_t println (unsigned int num)
Print unsigned integer to serial port with newline.
size_t println (unsigned int num, PrintFormat format)
Print unsigned integer to serial port with format and newline.
size_t println (double num, int decimals=2)
Print floating-point number to serial port with newline.
size_t println ()
Print newline only.
std::string readString ()
Read all available data into string.
std::string readStringUntil (char terminator)
Read data until specific character found.
void setTimeout (unsigned long milliseconds)
Set timeout for read operations.
void flush ()
Flush transmit buffer (wait for all data to be sent)
unsigned long getBaudRate () const
Get current baud rate.
Detailed Description
Arduino-compatible Serial communication class for Raspberry Pi.
This class provides UART communication compatible with Arduino's Serial API. It uses Linux termios for hardware serial ports (/dev/ttyUSB*, /dev/ttyACM*, /dev/ttyAMA*).
Note
Thread-safe: All operations are protected by internal mutex
Hardware serial: Uses actual UART, not software bit-banging
Example Usage (communicating with Arduino):
#include "Serial.hpp"
using namespace pipinpp;
int main() {
    // Open serial connection to Arduino at 9600 baud
    if (!Serial.begin(9600, "/dev/ttyUSB0")) {
        std::cerr << "Failed to open serial port\n";
        return 1;
    }
    // Send command to Arduino
    Serial.println("MOVE_FORWARD");
    // Wait for response
    delay(100);
    if (Serial.available()) {
        String response = Serial.readStringUntil('\n');
        std::cout << "Arduino says: " << response << "\n";
    }
    Serial.end();
    return 0;
}
Definition at line 89 of file Serial.hpp.
Constructor & Destructor Documentation
SerialPort()
pipinpp::SerialPort::SerialPort ()
Constructor.
Definition at line 24 of file Serial.cpp.
~SerialPort()
pipinpp::SerialPort::~SerialPort ()
Destructor - automatically closes port if open.
Definition at line 32 of file Serial.cpp.
References end().
Member Function Documentation
available()
int pipinpp::SerialPort::available ()
Get number of bytes available for reading.
Returns
Number of bytes in receive buffer
Note
Returns 0 if port not open or no data available
Definition at line 88 of file Serial.cpp.
References PIPINPP_LOG_ERROR.
begin()
bool pipinpp::SerialPort::begin (unsigned long baudRate, const std::string & device = "/dev/ttyUSB0")
Open serial port with specified baud rate.
Parameters
baudRate Communication speed (9600, 19200, 38400, 57600, 115200, etc.)
device Serial device path (default: "/dev/ttyUSB0")
Returns
true if port opened successfully, false on error
Common devices:
/dev/ttyUSB0 - USB-to-serial adapter (FTDI, CH340, etc.)
/dev/ttyACM0 - Arduino Uno/Mega (native USB)
/dev/ttyAMA0 - Raspberry Pi hardware UART (GPIO 14/15)
/dev/ttyS0 - Raspberry Pi mini UART (less accurate, avoid if possible)
Note
Multiple begin() calls are safe - will close existing connection first
User must be in 'dialout' group for /dev/tty* access
Definition at line 37 of file Serial.cpp.
References PIPINPP_LOG_ERROR, and PIPINPP_LOG_INFO.
end()
void pipinpp::SerialPort::end ()
Close serial port.
Note
Safe to call even if port not open
Definition at line 69 of file Serial.cpp.
References PIPINPP_LOG_INFO.
Referenced by ~SerialPort().
flush()
void pipinpp::SerialPort::flush ()
Flush transmit buffer (wait for all data to be sent)
Note
Blocks until all pending data transmitted
Definition at line 310 of file Serial.cpp.
getBaudRate()
unsigned long pipinpp::SerialPort::getBaudRate () const
Get current baud rate.
Returns
Baud rate, or 0 if port not open
Definition at line 319 of file Serial.cpp.
isOpen()
bool pipinpp::SerialPort::isOpen () const
Check if serial port is open and ready.
Returns
true if port is open, false otherwise
Definition at line 82 of file Serial.cpp.
peek()
int pipinpp::SerialPort::peek ()
Peek at next byte without removing from buffer.
Returns
Byte value (0-255), or -1 if no data available
Note
Does not advance read position
Definition at line 136 of file Serial.cpp.
print() [1/8]
size_t pipinpp::SerialPort::print (const std::string & data)
Print data to serial port (no newline)
Parameters
data String to print
Returns
Number of bytes written
Definition at line 182 of file Serial.cpp.
References write().
print() [2/8]
size_t pipinpp::SerialPort::print (double num, int decimals = 2)
Print floating-point number to serial port (no newline)
Parameters
num Number to print
decimals Number of decimal places (default: 2)
Returns
Number of bytes written
Definition at line 217 of file Serial.cpp.
References write().
print() [3/8]
size_t pipinpp::SerialPort::print (int num)
Print integer to serial port (no newline)
Parameters
num Integer to print
Returns
Number of bytes written
Definition at line 187 of file Serial.cpp.
References write().
print() [4/8]
size_t pipinpp::SerialPort::print (int num, PrintFormat format)
Print integer to serial port with format (no newline)
Parameters
num Integer to print
format Format: DEC (decimal), HEX (hexadecimal), OCT (octal), BIN (binary)
Returns
Number of bytes written
Example:
Serial.print(255, HEX);  // Prints "FF"
Serial.print(255, BIN);  // Prints "11111111"
Definition at line 192 of file Serial.cpp.
References write().
print() [5/8]
size_t pipinpp::SerialPort::print (long num)
Print long integer to serial port (no newline)
Parameters
num Long integer to print
Returns
Number of bytes written
Definition at line 197 of file Serial.cpp.
References write().
print() [6/8]
size_t pipinpp::SerialPort::print (long num, PrintFormat format)
Print long integer to serial port with format (no newline)
Parameters
num Long integer to print
format Format: DEC, HEX, OCT, BIN
Returns
Number of bytes written
Definition at line 202 of file Serial.cpp.
References write().
print() [7/8]
size_t pipinpp::SerialPort::print (unsigned int num)
Print unsigned integer to serial port (no newline)
Parameters
num Unsigned integer to print
Returns
Number of bytes written
Definition at line 207 of file Serial.cpp.
References write().
print() [8/8]
size_t pipinpp::SerialPort::print (unsigned int num, PrintFormat format)
Print unsigned integer to serial port with format (no newline)
Parameters
num Unsigned integer to print
format Format: DEC, HEX, OCT, BIN
Returns
Number of bytes written
Definition at line 212 of file Serial.cpp.
References write().
println() [1/9]
size_t pipinpp::SerialPort::println ()
Print newline only.
Returns
Number of bytes written (2: \r
)
Definition at line 266 of file Serial.cpp.
References write().
println() [2/9]
size_t pipinpp::SerialPort::println (const std::string & data)
Print data to serial port with newline.
Parameters
data String to print
Returns
Number of bytes written (including newline)
Definition at line 224 of file Serial.cpp.
References write().
println() [3/9]
size_t pipinpp::SerialPort::println (double num, int decimals = 2)
Print floating-point number to serial port with newline.
Parameters
num Number to print
decimals Number of decimal places (default: 2)
Returns
Number of bytes written
Definition at line 259 of file Serial.cpp.
References write().
println() [4/9]
size_t pipinpp::SerialPort::println (int num)
Print integer to serial port with newline.
Parameters
num Integer to print
Returns
Number of bytes written
Definition at line 229 of file Serial.cpp.
References write().
println() [5/9]
size_t pipinpp::SerialPort::println (int num, PrintFormat format)
Print integer to serial port with format and newline.
Parameters
num Integer to print
format Format: DEC, HEX, OCT, BIN
Returns
Number of bytes written
Definition at line 234 of file Serial.cpp.
References write().
println() [6/9]
size_t pipinpp::SerialPort::println (long num)
Print long integer to serial port with newline.
Parameters
num Long integer to print
Returns
Number of bytes written
Definition at line 239 of file Serial.cpp.
References write().
println() [7/9]
size_t pipinpp::SerialPort::println (long num, PrintFormat format)
Print long integer to serial port with format and newline.
Parameters
num Long integer to print
format Format: DEC, HEX, OCT, BIN
Returns
Number of bytes written
Definition at line 244 of file Serial.cpp.
References write().
println() [8/9]
size_t pipinpp::SerialPort::println (unsigned int num)
Print unsigned integer to serial port with newline.
Parameters
num Unsigned integer to print
Returns
Number of bytes written
Definition at line 249 of file Serial.cpp.
References write().
println() [9/9]
size_t pipinpp::SerialPort::println (unsigned int num, PrintFormat format)
Print unsigned integer to serial port with format and newline.
Parameters
num Unsigned integer to print
format Format: DEC, HEX, OCT, BIN
Returns
Number of bytes written
Definition at line 254 of file Serial.cpp.
References write().
read()
int pipinpp::SerialPort::read ()
Read single byte from serial port (blocking)
Returns
Byte value (0-255), or -1 if no data available or timeout
Note
Respects timeout set by setTimeout()
Definition at line 105 of file Serial.cpp.
Referenced by readString(), and readStringUntil().
readString()
std::string pipinpp::SerialPort::readString ()
Read all available data into string.
Returns
String containing all received data
Note
Reads until no more data available or timeout
Definition at line 271 of file Serial.cpp.
References read().
readStringUntil()
std::string pipinpp::SerialPort::readStringUntil (char terminator)
Read data until specific character found.
Parameters
terminator Character to stop at (not included in result)
Returns
String containing data up to terminator
Note
Commonly used with '
' to read line-by-line from Arduino
Definition at line 286 of file Serial.cpp.
References read().
setTimeout()
void pipinpp::SerialPort::setTimeout (unsigned long milliseconds)
Set timeout for read operations.
Parameters
milliseconds Timeout in milliseconds (0 = non-blocking, default: 1000)
Note
Affects read(), readString(), readStringUntil()
Definition at line 304 of file Serial.cpp.
write() [1/3]
size_t pipinpp::SerialPort::write (const std::string & str)
Write string to serial port.
Parameters
str String to send
Returns
Number of bytes written
Definition at line 177 of file Serial.cpp.
References write().
write() [2/3]
size_t pipinpp::SerialPort::write (const uint8_t * buffer, size_t size)
Write buffer of bytes to serial port.
Parameters
buffer Pointer to data buffer
size Number of bytes to send
Returns
Number of bytes actually written
Definition at line 165 of file Serial.cpp.
References write().
write() [3/3]
size_t pipinpp::SerialPort::write (uint8_t byte)
Write single byte to serial port.
Parameters
byte Byte to send (0-255)
Returns
Number of bytes written (1 on success, 0 on failure)
Definition at line 153 of file Serial.cpp.
Referenced by print(), println(), and write().
The documentation for this class was generated from the following files:
include/Serial.hpp
src/Serial.cpp